### ISSUE TITLE
Close Button Missing

### ISSUE THREAD

**Issue by brijeshdobariya** [Constantine-k/brackets-psd-layer-viewer#2]
hello @Constantine-k 
your add on is very use full for web designer. its a amazing feature for Brackets Editor to make Unique.
But there are missing some things, there is no option for remove current PSD and user can not add new PSD file.
thanks and regard
brijesh dobariya

**Comment by Constantine-k** [comment]
Hello @brijeshdobariya
Thank you. I agree that this feature is really necessary, so I think I'm gonna add it soon.

**Comment by brijeshdobariya** [comment]
thanks @Constantine-k

**Comment by Constantine-k** [comment]
For now for opening new PSD file you can refresh Brackets (F5 on Windows or Command + R on Mac), I know that it's a bit annoying...

**Comment by brijeshdobariya** [comment]
thanks for instant solution

**Comment by Constantine-k** [comment]
The site's author (Keyang Xiang) has added Close button
